name    'puppet-rhews'
version '0.1.0'
source  'Conduct AS'
author  'Bjørn Ola Smievoll <bos@conduct.no>'
license 'Apache License, Version 2.0'
summary 'RH EWS 2'
description 'Module for Red Hat Enterprise Web Server 2 (EWS 2)'
project_page 'https://github.com/ConductAS/puppet-rhews'
